###

POST http://127.0.0.1:8071/api/v1/generator/all
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/projects/spring-axon-rabbitmq-web-jpa-starter/src/main/java/com/groupe2cs/bizyhub/chatMessage",
  "definition": {
	"name": "ChatMessage",
	"table": "chat-messages",
	"fields": [
	  {
		"name": "id",
		"type": "String"
	  },
	  {
		"name": "content",
		"type": "String",
		"columnDefinition" : "TEXT"
	  },
	  {
		"name": "user",
		"type": "String"
	  },
	  {
		"name": "files",
		"type": "files",
        "isFiles": true,
		"columnDefinition" : "TEXT"
	  }
	]
  }
}

###
