
###
POST http://127.0.0.1:8071/api/v1/generator/angular
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/labs/tauri/tauri-pos/src/app/features",
  "definition": {
	"name": "Category",
	"table": "categories",
	"plural": "categories",
	"title": "Catégorie",
	"hasType": true,
    "tauri": true,
	"fields": [
	  {
		"name": "id",
		"type": "String"
	  },
	  {
		"name": "name",
		"focus": true,
		"displayName": "Nom",
		"type": "String"
	  },
	  {
		"name": "typeCategoryRaw",
		"type": "String",
		"entityType": "enum"
	  },
	  {
		"name": "details",
		"type": "String",
		"displayName": "Description",
		"nullable": true
	  },
	  {
		"name": "isActive",
		"type": "Boolean",
		"defaultValue": true
	  }
	]
  }
}


###
POST http://127.0.0.1:8071/api/v1/generator/angular
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/labs/tauri/tauri-pos/src/app/features",
  "definition": {
	"name": "Transaction",
	"table": "transactions",
	"plural": "transactions",
	"tauri": true,
	"header": "account",
	"hasSummary": true,
	"hasType": true,
	"hasDate": true,
	"transactional": true,
	"hasCategory": true,
	"title": "Transaction",
	"fields": [
	  {
		"name": "id",
		"inputType": "hidden",
		"type": "String"
	  },
	  {
		"name": "amount",
		"type": "Double",
		"inputType": "number",
		"focus": true,
		"displayName": "Montant",
		"indicators": [
		  "sum"
		]
	  },
	  {
		"name": "name",
		"type": "String",
		"inputType": "text",
		"defaultValue": "\"Pas de motif\"",
		"displayName": "Motif"
	  },
	  {
		"name": "details",
		"type": "String",
		"inputType": "text",
		"defaultValue": "\"Pas de description\"",
		"displayName": "Description",
		"nullable": true
	  },
	  {
		"name": "isActive",
		"inputType": "checkbox",
		"displayName": "Activé",
		"type": "Boolean",
		"defaultValue": true
	  },
	  {
		"name": "account",
		"displayName": "Compte",
		"inputType": "hidden",
		"entityType": "Account",
		"type": "String",
		"relation": "manyToOne",
		"nullable": true
	  },
	  {
		"name": "category",
		"inputType": "hidden",
		"displayName": "Category",
		"entityType": "Category",
		"type": "String",
		"relation": "manyToOne",
		"nullable": true
	  },
	  {
		"inputType": "text",
		"name": "typeTransactionRaw",
		"type": "String",
		"displayName": "type",
		"entityType": "enum"
	  },
	  {
		"inputType": "date",
		"name": "dateTransaction",
		"type": "Date",
		"displayName": "Date transaction",
		"defaultValue": "new Date().toISOString().substring(0, 10)",
		"nullable": true
	  }
	]
  }
}

###