POST http://127.0.0.1:8071/api/v1/generator/angular
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/labs/angular/topall-angular/src/app/features",
  "definition": {
	"name": "Account",
	"table": "accounts",
	"title": "Compte",
	"shared": true,
	"fields": [
	  {
		"name": "id",
		"type": "String"
	  },
	  {
		"name": "name",
		"type": "String",
		"focus": true,
		"displayName": "Nom"
	  },
	  {
		"name": "details",
		"type": "String",
		"displayName": "Description",
		"nullable": true
	  },
	  {
		"name": "currency",
		"type": "String",
		"displayName": "Devise",
		"defaultValue": "\"XOF\""
	  },
	  {
		"name": "currentBalance",
		"type": "Double",
		"displayName": "Solde de départ",
		"defaultValue": 0.0
	  },
	  {
		"name": "previousBalance",
		"type": "Double",
		"defaultValue": 0.0
	  },
	  {
		"name": "isActive",
		"type": "Boolean",
		"displayName": "Est active",
		"defaultValue": true
	  }
	]
  }
}

###
POST http://127.0.0.1:8071/api/v1/generator/angular
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/labs/angular/topall-angular/src/app/features",
  "definition": {
	"name": "AccountUser",
	"bind": "username",
	"table": "account_users",
	"title": "Comptes partagés",
	"isPremium": true,
	"fields": [
	  {
		"name": "id",
		"type": "String"
	  },
	  {
		"name": "name",
		"type": "String",
		"displayName": "Message"
	  },
	  {
		"name": "account",
		"displayName": "Compte",
		"entityType": "Account",
		"type": "String",
		"relation": "manyToOne",
		"nullable": true
	  },
	  {
		"name": "username",
		"displayName": "Partager avec (Nom identifiant)",
		"type": "String"
	  },
	  {
		"name": "details",
		"displayName": "Description",
		"type": "String",
		"nullable": true
	  },
	  {
		"name": "isActive",
		"type": "Boolean",
		"defaultValue": true
	  }
	]
  }
}

###
POST http://127.0.0.1:8071/api/v1/generator/angular
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/labs/angular/topall-angular/src/app/features",
  "definition": {
	"name": "Category",
	"table": "categories",
	"title": "Catégorie",
	"hasType": true,
	"fields": [
	  {
		"name": "id",
		"type": "String"
	  },
	  {
		"name": "name",
		"focus": true,
		"displayName": "Nom",
		"type": "String"
	  },
	  {
		"name": "typeCategoryRaw",
		"type": "String",
		"entityType": "enum"
	  },
	  {
		"name": "details",
		"type": "String",
		"displayName": "Description",
		"nullable": true
	  },
	  {
		"name": "isActive",
		"type": "Boolean",
		"defaultValue": true
	  }
	]
  }
}

###
POST http://127.0.0.1:8071/api/v1/generator/angular
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/labs/angular/topall-angular/src/app/features",
  "definition": {
	"name": "Transaction",
	"table": "transactions",
	"header": "account",
	"hasSummary": true,
	"hasType": true,
	"hasDate": true,
	"transactional": true,
	"hasCategory": true,
	"title": "Transaction",
	"fields": [
	  {
		"name": "id",
        "inputType": "hidden",
		"type": "String"
	  },
	  {
		"name": "amount",
		"type": "Double",
		"inputType": "number",
		"focus": true,
		"displayName": "Montant",
		"indicators": [
		  "sum"
		]
	  },
	  {
		"name": "name",
		"type": "String",
		"inputType": "text",
		"defaultValue": "\"Pas de motif\"",
		"displayName": "Motif"
	  },
	  {
		"name": "details",
		"type": "String",
		"inputType": "text",
		"defaultValue": "\"Pas de description\"",
		"displayName": "Description",
		"nullable": true
	  },
	  {
		"name": "isActive",
		"inputType": "checkbox",
		"displayName": "Activé",
		"type": "Boolean",
		"defaultValue": true
	  },
	  {
		"name": "account",
		"displayName": "Compte",
		"inputType": "hidden",
		"entityType": "Account",
		"type": "String",
		"relation": "manyToOne",
		"nullable": true
	  },
	  {
		"name": "category",
		"inputType": "hidden",
		"displayName": "Category",
		"entityType": "Category",
		"type": "String",
		"relation": "manyToOne",
		"nullable": true
	  },
	  {
		"inputType": "text",
		"name": "typeTransactionRaw",
		"type": "String",
		"displayName": "type",
		"entityType": "enum"
	  },
	  {
		"inputType": "date",
		"name": "dateTransaction",
		"type": "Date",
		"displayName": "Date transaction",
		"defaultValue": "new Date().toISOString().substring(0, 10)",
		"nullable": true
	  }
	]
  }
}

###

POST http://127.0.0.1:8071/api/v1/generator/angular
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/labs/angular/topall-angular/src/app/features",
  "definition": {
	"name": "Setting",
	"table": "settings",
	"title": "Paramètre",
	"multiTenant": true,
	"auditable": true,
	"apiPrefix": "admin",
	"isPublic": true,
	"fields": [
	  {
		"name": "id",
		"type": "String"
	  },
	  {
		"name": "name",
		"focus": true,
		"type": "String",
		"displayName": "Clé",
		"isLowerCase": true
	  },
	  {
		"name": "value",
		"type": "String",
		"displayName": "Valeur"
	  },
	  {
		"name": "locale",
		"type": "String",
		"displayName": "Langue",
		"isLowerCase": true
	  },
	  {
		"name": "details",
		"type": "String",
		"displayName": "Description",
		"nullable": true,
		"defaultValue": "\"NA\""
	  },
	  {
		"name": "isActive",
		"type": "Boolean",
		"defaultValue": true
	  }
	]
  }
}

###


POST http://127.0.0.1:8071/api/v1/generator/angular
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/labs/angular/topall-angular/src/app/features",
  "definition": {
	"name": "Chat",
	"table": "chat",
	"title": "Chat",
	"header": "account",
	"hasSummary": false,
	"hasType": false,
	"hasDate": false,
	"transactional": false,
	"hasCategory": false,
	"isAutoSave": true,
	"isChat": true,
	"hasFiles": true,
	"fields": [
	  {
		"name": "id",
		"type": "String"
	  },
	  {
		"name": "messages",
		"focus": true,
		"type": "String",
		"displayName": "Message"
	  },
	  {
		"name": "responses",
		"type": "String",
		"displayName": "Réponses",
		"nullable": true
	  },
	  {
		"name": "responsesJson",
		"type": "String",
		"columnDefinition": "Text",
		"nullable": true
	  },
	  {
		"name": "state",
		"type": "String",
		"nullable": true
	  },
	  {
		"name": "account",
		"entityType": "Account",
		"type": "String",
		"relation": "manyToOne",
		"nullable": true
	  },
	  {
		"name": "files",
		"type": "files",
		"isFiles": true,
		"columnDefinition" : "TEXT"
	  }
	]
  }
}

###


###

POST http://127.0.0.1:8071/api/v1/generator/angular
Accept: application/x-ndjson
Content-Type: application/json

{

  "outputDir": "/Users/pcoundia/labs/angular/topall-angular/src/app/features",
  "definition": {
	"name": "FileManager",
	"table": "file_manager",
	"title": "FileManager",
	"isFileManager": true,
	"fields": [
	  { "name": "id", "type": "String" },
	  { "name": "name", "type": "String" },
	  { "name": "details", "type": "String",
		"columnDefinition": "Text",
		"nullable": true },
	  { "name": "objectId", "type": "String" ,"nullable": true },
	  { "name": "objectName", "type": "String" ,"nullable": true },
	  { "name": "originalName", "type": "String" ,"nullable": true,"displayName": "Nom" },
	  { "name": "mimeType", "type": "String","nullable": true },
	  { "name": "size", "type": "Long" ,"nullable": true},
	  { "name": "path", "type": "String" ,"nullable": true},
	  { "name": "uri", "type": "String","nullable": true },
	  { "name": "isPublic", "type": "Boolean", "nullable": true }
	]
  }
}

###

