###

POST http://127.0.0.1:8071/api/v1/generator/swiftui
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/labs/swift/ges-depense/ges-depense",
  "definition": {
	"name": "Account",
	"table": "accounts",
	"shared": true,
	"fields": [
	  { "name": "id", "type": "String" },
	  { "name": "name",  "type": "String", "displayName": "Name"  },
	  { "name": "currency", "type": "String" , "displayName": "Currency", "defaultValue": "\"XOF\"" },
	  { "name": "currentBalance", "type": "Double", "displayName": "Balance", "defaultValue": 0.0 },
	  { "name": "previousBalance", "type": "Double", "defaultValue": 0.0 },
	  { "name": "details", "type": "String", "displayName": "details", "nullable": true},
	  { "name": "isActive", "type": "Boolean", "displayName": "Active", "defaultValue": true }
	]
  }
}

###
