###

POST http://127.0.0.1:8071/api/v1/generator/swiftui
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/labs/swift/ges-depense/ges-depense",
  "definition": {
	"name": "Product",
	"table": "products",
	"title": "Product Management",
	"fields": [
	  { "name": "id", "type": "String" },
	  { "name": "name", "type": "String", "displayName": "Name"},
	  { "name": "price", "type": "Double",
		"defaultValue": 0.0, "displayName": "Price"
	  },
	  { "name": "details", "type": "String",
        "nullable": true,"defaultValue": "\"NA\""
	  },
	  { "name": "isActive", "type": "Boolean", "defaultValue": true }
	]
  }
}

###
