###

POST http://127.0.0.1:8071/api/v1/generator/swiftui
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/labs/swift/ges-depense/ges-depense",
  "definition": {
	"name": "Sale",
	"table": "sales",
    "title": "Sales Management",
	"fields": [
	  {
		"name": "id",
		"type": "String"
	  },
	  {
		"name": "name",
		"type": "String",
        "displayName": "Name"
	  },
	  {
		"name": "amount",
		"type": "Double",
		"displayName": "Amount",
		"indicators": ["sum"]
	  },
	  {
		"name": "details",
		"type": "String",
		"displayName": "Description",
		"unique": true,
		"nullable": true
	  },
	  {
		"name": "isActive",
		"displayName": "Activé",
		"type": "Boolean",
		"defaultValue": true
	  },
	  {
		"name": "product",
		"type": "Product",
        "relation": "manyToOne",
		"displayName": "Product"
	  }
	]
  }
}

###
