POST http://127.0.0.1:8071/api/v1/generator/swiftui
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/labs/swift/ges-depense/ges-depense",
  "definition": {
	"name": "Setting",
	"table": "settings",
	"multiTenant": true,
	"auditable": true,
	"fields": [
	  { "name": "id", "type": "String" },
	  { "name": "name", "type": "String", "unique": true },
	  { "name": "details", "type": "String", "displayName": "details", "nullable": true},

	  { "name": "stringValue", "type": "String" },
	  { "name": "descriptions", "type": "String",

		"nullable": true
	  },
	  { "name": "isActive", "type": "Boolean", "defaultValue": true }
	],
	"stack": [
	  "Security"
	]
  }
}
