POST http://127.0.0.1:8071/api/v1/generator/swiftui
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/labs/swift/ges-depense/ges-depense",
  "definition": {
	"name": "Transaction",
	"table": "transactions",
	"shared": true,
	"header": "account",
    "hasSummary": true,
    "hasType": true,
    "hasDate": true,

	"title": "Transaction Management",
	"fields": [
	  {
		"name": "id",
		"type": "String"
	  },
	  {
		"name": "name",
		"type": "String",
		"displayName": "Name"
	  },
	  {
		"name": "amount",
		"type": "Double",
		"displayName": "Amount",
		"indicators": [
		  "sum"
		]
	  },
	  {
		"name": "details",
		"type": "String",
		"displayName": "Description",
		"unique": true,
		"nullable": true
	  },
	  {
		"name": "isActive",
		"displayName": "Activé",
		"type": "Boolean",
		"defaultValue": true
	  },
	  {
		"name": "account",
		"displayName": "account",
		"entityType": "Account",
		"type": "String",
		"relation": "manyToOne",
		"nullable": true
	  },
	  {
		"name": "category",
		"displayName": "Categories",
		"entityType": "Category",
		"type": "String",
		"relation": "manyToOne",
		"nullable": true
	  },
	  {
        "name": "typeTransactionRaw",
        "type": "String",
		"displayName": "type",
		"defaultValue": "nil",
		"entityType": "enum"
	  },
	  {
		"name": "dateTransaction",
		"type": "Date",
        "displayName": "Date",
		"defaultValue": "date()",
		"nullable": true
	  }
	]
  }
}

###
