###
POST http://127.0.0.1:8071/api/v1/generator/all
Accept: application/x-ndjson
Content-Type: application/json

{

  "outputDir": "/Users/pcoundia/projects/spring-axon-rabbitmq-web-jpa-starter/src/main/java/com/groupe2cs/bizyhub/categories",
  "definition": {
	"name": "Category",
	"table": "categories",
	"fields": [
	  { "name": "id", "type": "String" },
	  { "name": "name", "type": "String" },
	  { "name": "typeCategoryRaw", "type": "String", "nullable": true },
	  { "name": "details", "type": "String", "displayName": "details", "nullable": true},
	  { "name": "isActive", "type": "Boolean", "defaultValue": true }
	]
  }
}
