POST http://127.0.0.1:8071/api/v1/generator/all
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/projects/spring-axon-rabbitmq-web-jpa-starter/src/main/java/com/groupe2cs/bizyhub/transactions",
  "definition": {
	"name": "Transaction",
	"shared": true,
	"table": "transactions",
	"fields": [
	  {
		"name": "id",
		"type": "String"
	  },
	  {
		"name": "name",
		"type": "String"
	  },
	  {
		"name": "amount",
		"type": "Double"
	  },
	  {
		"name": "details",
		"type": "String",
		"nullable": true
	  },
	  {
		"name": "isActive",
		"type": "Boolean",
		"defaultValue": true
	  },
	  {
		"name": "account",
		"type": "com.groupe2cs.bizyhub.accounts.infrastructure.entity.Account",
		"relation": "manyToOne",
		"nullable": true
	  }
	,
	  {
		"name": "category",
		"type": "com.groupe2cs.bizyhub.categories.infrastructure.entity.Category",
		"relation": "manyToOne",
		"nullable": true
	  },
	  { "name": "typeTransactionRaw", "type": "String", "nullable": true },
	  {
		"name": "dateTransaction",
		"type": "java.time.Instant",
		"defaultValue": "java.time.Instant.now()",
		 "nullable": true

	  }
	]
  }
}
