###

POST http://127.0.0.1:8071/api/v1/generator/all
Accept: application/x-ndjson
Content-Type: application/json

{
  "outputDir": "/Users/pcoundia/projects/spring-axon-rabbitmq-web-jpa-starter/src/main/java/com/groupe2cs/bizyhub/transactions",
  "definition": {
	"name": "Transaction",
	"table": "transactions",
    "auditable": true,
	"fields": [
	  {
        "name": "id",
        "type": "String"
      },
	  {
        "name": "reference",
        "type": "String",
        "nullable": true,
		"unique": true
	  },
	  { "name": "amount", "type": "Double" }
	],
    "stack": [
      "Security"
    ]
  }
}

###
